/** 1030870080 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef VPNP_CUR1_INST_STATIC_H
#define VPNP_CUR1_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_328	(*((double *) &instData [328]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_320	(*((double *) &instData [320]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_vp_vn_312	(*((double *) &instData [312]))	/* Branch Load Group : Size = 8 bytes. */
#define _tgaintest_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _cur1_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _testvolt_192	(*((double *) &instData [192]))	/* VT_REAL : Size = 8 bytes. */
#define _v1_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _nf_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _areae_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _js3_esdvpnp_wf_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _tgainr_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* VPNP_CUR1_INST_STATIC_H */
