/** 1470379590 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "vpnp_cur1_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int vpnp_cur1_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_vp_vn_320 = 0.0;
_Static_d_by_dv_vp_vn_312 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_192) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 33);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_2 = ((1.00000000000000000000e+00));(_v1_152) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 34);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_tgainr_56) * ((1.00000000000000000000e+00)))));(_tgaintest_272) = __tempValueResultStatic;}if (((_v1_152) >= ((0.00000000000000000000e+00)))){ahdlDoSetLineNum ((long) 37);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * ((ahdlPow((_v1_152), ((1.30000000000000004441e+00))))))));__tmpStkVar_3 = (((((((_tgaintest_272)) * ((((((((_js3_esdvpnp_wf_80)) * ((_areae_104))))) * ((_nf_128)))))))) * ((((((1.30000000000000004441e+00))) * (((((__tmpStkVar_2)) * (((ahdlPowDeriv((_v1_152), ((3.00000000000000044409e-01))))))))))))));(_cur1_232) = __tempValueResultStatic;}}else{ahdlDoSetLineNum ((long) 39);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * (((__INT_TO_DBL((-1L)) * ((ahdlPow(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((1.30000000000000004441e+00)))))))))));__tmpStkVar_3 = (((((((_tgaintest_272)) * ((((((((_js3_esdvpnp_wf_80)) * ((_areae_104))))) * ((_nf_128)))))))) * ((((__INT_TO_DBL((-1L))) * ((((((1.30000000000000004441e+00))) * (((((((__tmpStkVar_4 >= 0) ? (__tmpStkVar_2) : (-__tmpStkVar_2)))) * (((ahdlPowDeriv(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((3.00000000000000044409e-01)))))))))))))))));(_cur1_232) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 41);(_I_Static_vp_vn_320) += (_cur1_232);_Static_d_by_dv_vp_vn_312 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 42);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_vp_12] -= _I_Static_vp_vn_320;
      ahdlStaticRHS[_vn_20] += _I_Static_vp_vn_320;
      ahdlStaticRHS_AbsSum[_vp_12] += ABS(_I_Static_vp_vn_320);
      ahdlStaticRHS_AbsSum[_vn_20] += ABS(_I_Static_vp_vn_320);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 304),_Static_d_by_dv_vp_vn_312);
    return __msgSeverity__;
} /** end of vpnp_cur1_DcFuncDerLoad **/

int vpnp_cur1_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_vp_vn_320 = 0.0;
_Static_d_by_dv_vp_vn_312 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_testvolt_192) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 33);(_v1_152) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 34);(_tgaintest_272) = ((((_tgainr_56) * ((1.00000000000000000000e+00)))));if (((_v1_152) >= ((0.00000000000000000000e+00)))){ahdlDoSetLineNum ((long) 37);(_cur1_232) = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * ((ahdlPow((_v1_152), ((1.30000000000000004441e+00))))))));}else{ahdlDoSetLineNum ((long) 39);(_cur1_232) = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * (((__INT_TO_DBL((-1L)) * ((ahdlPow(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((1.30000000000000004441e+00)))))))))));}ahdlDoSetLineNum ((long) 41);(_I_Static_vp_vn_320) += (_cur1_232);}ahdlDoSetLineNum ((long) 42);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_vp_12] -= _I_Static_vp_vn_320;
      ahdlStaticRHS[_vn_20] += _I_Static_vp_vn_320;
      ahdlStaticRHS_AbsSum[_vp_12] += ABS(_I_Static_vp_vn_320);
      ahdlStaticRHS_AbsSum[_vn_20] += ABS(_I_Static_vp_vn_320);
   }

    return __msgSeverity__;
} /** end of vpnp_cur1_DcFuncLoad **/

int vpnp_cur1_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_vp_vn_320 = 0.0;
_Static_d_by_dv_vp_vn_312 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_192) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 33);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_2 = ((1.00000000000000000000e+00));(_v1_152) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 34);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_tgainr_56) * ((1.00000000000000000000e+00)))));(_tgaintest_272) = __tempValueResultStatic;}if (((_v1_152) >= ((0.00000000000000000000e+00)))){ahdlDoSetLineNum ((long) 37);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * ((ahdlPow((_v1_152), ((1.30000000000000004441e+00))))))));__tmpStkVar_3 = (((((((_tgaintest_272)) * ((((((((_js3_esdvpnp_wf_80)) * ((_areae_104))))) * ((_nf_128)))))))) * ((((((1.30000000000000004441e+00))) * (((((__tmpStkVar_2)) * (((ahdlPowDeriv((_v1_152), ((3.00000000000000044409e-01))))))))))))));(_cur1_232) = __tempValueResultStatic;}}else{ahdlDoSetLineNum ((long) 39);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * (((__INT_TO_DBL((-1L)) * ((ahdlPow(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((1.30000000000000004441e+00)))))))))));__tmpStkVar_3 = (((((((_tgaintest_272)) * ((((((((_js3_esdvpnp_wf_80)) * ((_areae_104))))) * ((_nf_128)))))))) * ((((__INT_TO_DBL((-1L))) * ((((((1.30000000000000004441e+00))) * (((((((__tmpStkVar_4 >= 0) ? (__tmpStkVar_2) : (-__tmpStkVar_2)))) * (((ahdlPowDeriv(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((3.00000000000000044409e-01)))))))))))))))));(_cur1_232) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 41);(_I_Static_vp_vn_320) += (_cur1_232);_Static_d_by_dv_vp_vn_312 += (__tmpStkVar_3);}ahdlDoSetLineNum ((long) 42);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_vp_12] -= _I_Static_vp_vn_320;
      ahdlStaticRHS[_vn_20] += _I_Static_vp_vn_320;
      ahdlStaticRHS_AbsSum[_vp_12] += ABS(_I_Static_vp_vn_320);
      ahdlStaticRHS_AbsSum[_vn_20] += ABS(_I_Static_vp_vn_320);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 304),_Static_d_by_dv_vp_vn_312);
    return __msgSeverity__;
} /** end of vpnp_cur1_TranFuncDerLoad **/

int vpnp_cur1_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_vp_vn_320 = 0.0;
_Static_d_by_dv_vp_vn_312 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 32);ahdlDoSetLineNum ((long) 32);(_testvolt_192) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 33);(_v1_152) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 34);(_tgaintest_272) = ((((_tgainr_56) * ((1.00000000000000000000e+00)))));if (((_v1_152) >= ((0.00000000000000000000e+00)))){ahdlDoSetLineNum ((long) 37);(_cur1_232) = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * ((ahdlPow((_v1_152), ((1.30000000000000004441e+00))))))));}else{ahdlDoSetLineNum ((long) 39);(_cur1_232) = (((((((_tgaintest_272) * (((((((_js3_esdvpnp_wf_80) * (_areae_104)))) * (_nf_128))))))) * (((__INT_TO_DBL((-1L)) * ((ahdlPow(((ahdlFabs(__tmpStkVar_4 = (_v1_152)))), ((1.30000000000000004441e+00)))))))))));}ahdlDoSetLineNum ((long) 41);(_I_Static_vp_vn_320) += (_cur1_232);}ahdlDoSetLineNum ((long) 42);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_vp_12] -= _I_Static_vp_vn_320;
      ahdlStaticRHS[_vn_20] += _I_Static_vp_vn_320;
      ahdlStaticRHS_AbsSum[_vp_12] += ABS(_I_Static_vp_vn_320);
      ahdlStaticRHS_AbsSum[_vn_20] += ABS(_I_Static_vp_vn_320);
   }

    return __msgSeverity__;
} /** end of vpnp_cur1_TranFuncLoad **/

int vpnp_cur1_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of vpnp_cur1_NoiseLoadBiasDep **/

