/** 4021131791 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef BSOURCE_7_INST_STATIC_H
#define BSOURCE_7_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _V_Dynamic_hn1_520	(*((double *) &instData [520]))	/* Branch Reln : Size = 8 bytes. */
#define _V_Static_hn1_512	(*((double *) &instData [512]))	/* Branch Reln : Size = 8 bytes. */
#define _hn1_flow_496	(*((long *) &instData [496]))	/* Hidden Node : Size = 4 bytes. */
#define _I_Dynamic_bs_p1_bs_p2_488	(*((double *) &instData [488]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_bs_p1_bs_p2_480	(*((double *) &instData [480]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_ic_br_472	(*((double *) &instData [472]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_hn1_456	(*((double *) &instData [456]))	/* Branch Load Group : Size = 8 bytes. */
#define _Dynamic_d_by_dv_ic_br_440	(*((double *) &instData [440]))	/* Branch Load Group : Size = 8 bytes. */
#define _hn1_424	(*((long *) &instData [424]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_par_4_408	(*((double *) &instData [408]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_3_384	(*((double *) &instData [384]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_2_360	(*((double *) &instData [360]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_1_336	(*((double *) &instData [336]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_0_312	(*((double *) &instData [312]))	/* VT_REAL : Size = 8 bytes. */
#define _cap_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _Txm_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _m_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _Tx_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _T_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _trise_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _tc2_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _tc1_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _tnom_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _temp_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_p2_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_p1_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* BSOURCE_7_INST_STATIC_H */
