/** 369122079 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "bsource_7_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int bsource_7_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_I_Static_bs_p1_bs_p2_480 = 0.0;
_Static_d_by_dv_hn1_456 = 0.0;
_Static_d_by_dv_ic_br_472 = 0.0;

/*  C Code Every Code. */{(_I_Static_bs_p1_bs_p2_480) += ((((_cap_272 = (((((((_bs_par_0_312) * ((((_bs_par_1_336) + ((((((((((_bs_par_2_360) * (_bs_par_3_384)))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))))))))) * (_Txm_248)))))) * ((getAcrossSolution1(_hn1_424)))));_Static_d_by_dv_hn1_456 += ((_cap_272 = (((((((_bs_par_0_312)) * (((((_bs_par_1_336)) + (((((((((((_bs_par_2_360)) * ((_bs_par_3_384))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - ((_bs_par_4_408)))))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - ((_bs_par_4_408)))))))))))))) * ((_Txm_248))))));_Static_d_by_dv_ic_br_472 += (((((((((((_bs_par_0_312))) * ((((((((((((_bs_par_2_360))) * (((_bs_par_3_384)))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - (((_bs_par_4_408))))))))) + (((((((((_bs_par_2_360))) * (((_bs_par_3_384)))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - (((_bs_par_4_408))))))))))))))) * (((_Txm_248)))))) * (((getAcrossSolution1(_hn1_424))))));}   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_bs_p1_12] -= _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS[_bs_p2_20] += _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS_AbsSum[_bs_p1_12] += ABS(_I_Static_bs_p1_bs_p2_480);
      ahdlStaticRHS_AbsSum[_bs_p2_20] += ABS(_I_Static_bs_p1_bs_p2_480);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 448),_Static_d_by_dv_hn1_456);
      ahdlInterAddStaticQuartet(*(void**)(instData + 464),_Static_d_by_dv_ic_br_472);
    ahdlInterSetAcrossQuan(      *(void **)(instData + 500),
       _hn1_424,       *(long*)(instData + 0),       _hn1_flow_496,      0   ,       1.0    );
    return __msgSeverity__;
} /** end of bsource_7_DcFuncDerLoad **/

int bsource_7_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_I_Static_bs_p1_bs_p2_480 = 0.0;
_Static_d_by_dv_hn1_456 = 0.0;
_Static_d_by_dv_ic_br_472 = 0.0;

/*  C Code Every Code. */{(_I_Static_bs_p1_bs_p2_480) += ((((_cap_272 = (((((((_bs_par_0_312) * ((((_bs_par_1_336) + ((((((((((_bs_par_2_360) * (_bs_par_3_384)))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))))))))) * (_Txm_248)))))) * ((getAcrossSolution1(_hn1_424)))));}   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_bs_p1_12] -= _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS[_bs_p2_20] += _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS_AbsSum[_bs_p1_12] += ABS(_I_Static_bs_p1_bs_p2_480);
      ahdlStaticRHS_AbsSum[_bs_p2_20] += ABS(_I_Static_bs_p1_bs_p2_480);
   }

    ahdlInterSetAcrossQuan(      *(void **)(instData + 500),
       _hn1_424,       *(long*)(instData + 0),       _hn1_flow_496,      0   ,       1.0    );
    return __msgSeverity__;
} /** end of bsource_7_DcFuncLoad **/

int bsource_7_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_I_Static_bs_p1_bs_p2_480 = 0.0;
_Static_d_by_dv_hn1_456 = 0.0;
_Static_d_by_dv_ic_br_472 = 0.0;
_V_Dynamic_hn1_520 = 0.0;
_Dynamic_d_by_dv_ic_br_440 = 0.0;

/*  C Code Every Code. */{(_V_Dynamic_hn1_520) += (getAcrossSolution2(_bs_p1_12, _bs_p2_20));_Dynamic_d_by_dv_ic_br_440 += ((1.00000000000000000000e+00));(_I_Static_bs_p1_bs_p2_480) += ((((_cap_272 = (((((((_bs_par_0_312) * ((((_bs_par_1_336) + ((((((((((_bs_par_2_360) * (_bs_par_3_384)))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))))))))) * (_Txm_248)))))) * ((getAcrossSolution1(_hn1_424)))));_Static_d_by_dv_hn1_456 += ((_cap_272 = (((((((_bs_par_0_312)) * (((((_bs_par_1_336)) + (((((((((((_bs_par_2_360)) * ((_bs_par_3_384))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - ((_bs_par_4_408)))))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - ((_bs_par_4_408)))))))))))))) * ((_Txm_248))))));_Static_d_by_dv_ic_br_472 += (((((((((((_bs_par_0_312))) * ((((((((((((_bs_par_2_360))) * (((_bs_par_3_384)))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - (((_bs_par_4_408))))))))) + (((((((((_bs_par_2_360))) * (((_bs_par_3_384)))))) * ((((((getAcrossSolution2(_bs_p1_12, _bs_p2_20)))) - (((_bs_par_4_408))))))))))))))) * (((_Txm_248)))))) * (((getAcrossSolution1(_hn1_424))))));}   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_bs_p1_12] -= _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS[_bs_p2_20] += _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS_AbsSum[_bs_p1_12] += ABS(_I_Static_bs_p1_bs_p2_480);
      ahdlStaticRHS_AbsSum[_bs_p2_20] += ABS(_I_Static_bs_p1_bs_p2_480);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 448),_Static_d_by_dv_hn1_456);
      ahdlInterAddStaticQuartet(*(void**)(instData + 464),_Static_d_by_dv_ic_br_472);
   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_hn1_flow_496] += _V_Dynamic_hn1_520;
      ahdlDynamicRHS_AbsSum[_hn1_flow_496] += ABS(_V_Dynamic_hn1_520);
      }

    ahdlInterSetAcrossQuan(      *(void **)(instData + 500),
       _hn1_424,       *(long*)(instData + 0),       _hn1_flow_496,      0   ,       1.0    );
      /* do positive component */      ahdlInterAddDynamicElement(*(void**)(instData + 432), _Dynamic_d_by_dv_ic_br_440);
      /* do negative component */      ahdlInterAddDynamicElement(*(void**)(instData + 428), -_Dynamic_d_by_dv_ic_br_440);
    return __msgSeverity__;
} /** end of bsource_7_TranFuncDerLoad **/

int bsource_7_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


/*  Pre-Anal Load Code. */_I_Static_bs_p1_bs_p2_480 = 0.0;
_Static_d_by_dv_hn1_456 = 0.0;
_Static_d_by_dv_ic_br_472 = 0.0;
_V_Dynamic_hn1_520 = 0.0;
_Dynamic_d_by_dv_ic_br_440 = 0.0;

/*  C Code Every Code. */{(_V_Dynamic_hn1_520) += (getAcrossSolution2(_bs_p1_12, _bs_p2_20));(_I_Static_bs_p1_bs_p2_480) += ((((_cap_272 = (((((((_bs_par_0_312) * ((((_bs_par_1_336) + ((((((((((_bs_par_2_360) * (_bs_par_3_384)))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))) * (((((getAcrossSolution2(_bs_p1_12, _bs_p2_20))) - (_bs_par_4_408))))))))))))) * (_Txm_248)))))) * ((getAcrossSolution1(_hn1_424)))));}   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_bs_p1_12] -= _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS[_bs_p2_20] += _I_Static_bs_p1_bs_p2_480;
      ahdlStaticRHS_AbsSum[_bs_p1_12] += ABS(_I_Static_bs_p1_bs_p2_480);
      ahdlStaticRHS_AbsSum[_bs_p2_20] += ABS(_I_Static_bs_p1_bs_p2_480);
   }

   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_hn1_flow_496] += _V_Dynamic_hn1_520;
      ahdlDynamicRHS_AbsSum[_hn1_flow_496] += ABS(_V_Dynamic_hn1_520);
      }

    ahdlInterSetAcrossQuan(      *(void **)(instData + 500),
       _hn1_424,       *(long*)(instData + 0),       _hn1_flow_496,      0   ,       1.0    );
    return __msgSeverity__;
} /** end of bsource_7_TranFuncLoad **/

int bsource_7_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;


    return __msgSeverity__;
} /** end of bsource_7_NoiseLoadBiasDep **/

