/** 846167690 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef NCAP_FRCAP_INST_STATIC_H
#define NCAP_FRCAP_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_992	(*((double *) &instData [992]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_984	(*((double *) &instData [984]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Dynamic_d_by_dv_vp_vn_976	(*((double *) &instData [976]))	/* Branch Load Group : Size = 8 bytes. */
#define _testvolt_936	(*((double *) &instData [936]))	/* VT_REAL : Size = 8 bytes. */
#define _vnew_896	(*((double *) &instData [896]))	/* VT_REAL : Size = 8 bytes. */
#define _qnear_856	(*((double *) &instData [856]))	/* VT_REAL : Size = 8 bytes. */
#define _qtot_816	(*((double *) &instData [816]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc4_776	(*((double *) &instData [776]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc3_736	(*((double *) &instData [736]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc2_696	(*((double *) &instData [696]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc1_656	(*((double *) &instData [656]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc_616	(*((double *) &instData [616]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc_576	(*((double *) &instData [576]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc1_536	(*((double *) &instData [536]))	/* VT_REAL : Size = 8 bytes. */
#define _pc_ca_cap_512	(*((double *) &instData [512]))	/* VT_REAL : Size = 8 bytes. */
#define _pcm1_cap_488	(*((double *) &instData [488]))	/* VT_REAL : Size = 8 bytes. */
#define _pccor_464	(*((double *) &instData [464]))	/* VT_REAL : Size = 8 bytes. */
#define _pnear_m1_c_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _deltemp_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4tc_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3tc_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _pc0tc_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _pfrac_c_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _pcg_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _pc7_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _pc6_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _pc5_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _pc2_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _pc1_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf1_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _pcof_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* NCAP_FRCAP_INST_STATIC_H */
