/** 3520865387 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef NCAP_CUR_INST_STATIC_H
#define NCAP_CUR_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_704	(*((double *) &instData [704]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_696	(*((double *) &instData [696]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_vp_vn_688	(*((double *) &instData [688]))	/* Branch Load Group : Size = 8 bytes. */
#define _curp_648	(*((double *) &instData [648]))	/* VT_REAL : Size = 8 bytes. */
#define _curn_608	(*((double *) &instData [608]))	/* VT_REAL : Size = 8 bytes. */
#define _cur_568	(*((double *) &instData [568]))	/* VT_REAL : Size = 8 bytes. */
#define _testvolt_528	(*((double *) &instData [528]))	/* VT_REAL : Size = 8 bytes. */
#define _v1_488	(*((double *) &instData [488]))	/* VT_REAL : Size = 8 bytes. */
#define _pjtcn_464	(*((double *) &instData [464]))	/* VT_REAL : Size = 8 bytes. */
#define _pjtcp_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _pjtcdenp_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _pjtcdenn_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _deltemp_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _pareaj_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _pjgp0_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _pjp4_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _pjp3_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _pjp2_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _pjp1_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _pjgn0_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _pjn4_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _pjn3_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvdj_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _pjn2_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _pjn1_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* NCAP_CUR_INST_STATIC_H */
