/** 64180786 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef NCAP_CAP_INST_STATIC_H
#define NCAP_CAP_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_840	(*((double *) &instData [840]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_832	(*((double *) &instData [832]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Dynamic_d_by_dv_vp_vn_824	(*((double *) &instData [824]))	/* Branch Load Group : Size = 8 bytes. */
#define _testvolt_784	(*((double *) &instData [784]))	/* VT_REAL : Size = 8 bytes. */
#define _v1_744	(*((double *) &instData [744]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalfrl_704	(*((double *) &instData [704]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrgl1_664	(*((double *) &instData [664]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalcg_624	(*((double *) &instData [624]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc3_584	(*((double *) &instData [584]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc2_544	(*((double *) &instData [544]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc1_504	(*((double *) &instData [504]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc_464	(*((double *) &instData [464]))	/* VT_REAL : Size = 8 bytes. */
#define _pcofl_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _deltemp_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4tc_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3tc_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _pc0tc_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _pcof_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _pfrac_c_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _pcg_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _pcfl1_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _pc7_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _pc6_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _pc5_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _pc2_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _pc1_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* NCAP_CAP_INST_STATIC_H */
