/** 1641650672 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "ncap_cap_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int ncap_cap_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 62);ahdlDoSetLineNum ((long) 62);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_784) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 63);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_744) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 64);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_744))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_504) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 65);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))) * ((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))))))))))))));(_qcalc2_544) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 66);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_744) - (_pc7_224)))) * ((((_v1_744) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_744)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_744)) - ((_pc7_224)))) * ((((_v1_744)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_584) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 67);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((((_pcg_272) * (_p_pcvd_104)))) * (_pfrac_c_296)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_504) + (_qcalc2_544)))) - (_qcalc3_584)))))));__tmpStkVar_6 = (((((((((((((_pcg_272)) * ((_p_pcvd_104))))) * ((_pfrac_c_296))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_344)) * ((_deltemp_416))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_624) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 68);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl1_248) * (_v1_744))));__tmpStkVar_7 = ((((_pcfl1_248)) * ((__tmpStkVar_2))));(_qfrgl1_664) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 69);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_440)))) * (_qfrgl1_664))));__tmpStkVar_8 = (((((((((((2.00000000000000000000e+00))) * ((_p_pcvd_104))))) * ((_pcofl_440))))) * ((__tmpStkVar_7))));(_qcalfrl_704) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 70);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_624) + (_qcalfrl_704)))) * (_m_32))));__tmpStkVar_9 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_8))))) * ((_m_32))));(_qcalc_464) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 72);    return __msgSeverity__;
} /** end of ncap_cap_DcFuncDerLoad **/

int ncap_cap_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 62);ahdlDoSetLineNum ((long) 62);(_testvolt_784) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 63);(_v1_744) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 64);(_qcalc1_504) = ((((_pc1_56) * (_v1_744))));ahdlDoSetLineNum ((long) 65);(_qcalc2_544) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));ahdlDoSetLineNum ((long) 66);(_qcalc3_584) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_744) - (_pc7_224)))) * ((((_v1_744) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 67);(_qcalcg_624) = (((((((((((((_pcg_272) * (_p_pcvd_104)))) * (_pfrac_c_296)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_504) + (_qcalc2_544)))) - (_qcalc3_584)))))));ahdlDoSetLineNum ((long) 68);(_qfrgl1_664) = ((((_pcfl1_248) * (_v1_744))));ahdlDoSetLineNum ((long) 69);(_qcalfrl_704) = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_440)))) * (_qfrgl1_664))));ahdlDoSetLineNum ((long) 70);(_qcalc_464) = (((((((_qcalcg_624) + (_qcalfrl_704)))) * (_m_32))));}ahdlDoSetLineNum ((long) 72);    return __msgSeverity__;
} /** end of ncap_cap_DcFuncLoad **/

int ncap_cap_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_840 = 0.0;
_Dynamic_d_by_dv_vp_vn_824 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 62);ahdlDoSetLineNum ((long) 62);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_784) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 63);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_744) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 64);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_744))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_504) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 65);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))) * ((((_v1_744)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))))))))))))));(_qcalc2_544) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 66);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_744) - (_pc7_224)))) * ((((_v1_744) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_744)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_744)) - ((_pc7_224)))) * ((((_v1_744)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_584) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 67);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((((_pcg_272) * (_p_pcvd_104)))) * (_pfrac_c_296)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_504) + (_qcalc2_544)))) - (_qcalc3_584)))))));__tmpStkVar_6 = (((((((((((((_pcg_272)) * ((_p_pcvd_104))))) * ((_pfrac_c_296))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_344)) * ((_deltemp_416))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_624) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 68);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl1_248) * (_v1_744))));__tmpStkVar_7 = ((((_pcfl1_248)) * ((__tmpStkVar_2))));(_qfrgl1_664) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 69);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_440)))) * (_qfrgl1_664))));__tmpStkVar_8 = (((((((((((2.00000000000000000000e+00))) * ((_p_pcvd_104))))) * ((_pcofl_440))))) * ((__tmpStkVar_7))));(_qcalfrl_704) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 70);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_624) + (_qcalfrl_704)))) * (_m_32))));__tmpStkVar_9 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_8))))) * ((_m_32))));(_qcalc_464) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 71);(_I_Dynamic_vp_vn_840) += (_qcalc_464);_Dynamic_d_by_dv_vp_vn_824 += (__tmpStkVar_9);}ahdlDoSetLineNum ((long) 72);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_840;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_840;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_840);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_840);
   }

      ahdlInterAddDynamicQuartet(*(void**)(instData + 816),_Dynamic_d_by_dv_vp_vn_824);
    return __msgSeverity__;
} /** end of ncap_cap_TranFuncDerLoad **/

int ncap_cap_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_840 = 0.0;
_Dynamic_d_by_dv_vp_vn_824 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 62);ahdlDoSetLineNum ((long) 62);(_testvolt_784) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 63);(_v1_744) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 64);(_qcalc1_504) = ((((_pc1_56) * (_v1_744))));ahdlDoSetLineNum ((long) 65);(_qcalc2_544) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_v1_744) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));ahdlDoSetLineNum ((long) 66);(_qcalc3_584) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_744) - (_pc7_224)))) * ((((_v1_744) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 67);(_qcalcg_624) = (((((((((((((_pcg_272) * (_p_pcvd_104)))) * (_pfrac_c_296)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_504) + (_qcalc2_544)))) - (_qcalc3_584)))))));ahdlDoSetLineNum ((long) 68);(_qfrgl1_664) = ((((_pcfl1_248) * (_v1_744))));ahdlDoSetLineNum ((long) 69);(_qcalfrl_704) = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_440)))) * (_qfrgl1_664))));ahdlDoSetLineNum ((long) 70);(_qcalc_464) = (((((((_qcalcg_624) + (_qcalfrl_704)))) * (_m_32))));ahdlDoSetLineNum ((long) 71);(_I_Dynamic_vp_vn_840) += (_qcalc_464);}ahdlDoSetLineNum ((long) 72);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_840;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_840;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_840);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_840);
   }

    return __msgSeverity__;
} /** end of ncap_cap_TranFuncLoad **/

int ncap_cap_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of ncap_cap_NoiseLoadBiasDep **/

