/** 2408891510 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "ncap_frcap_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int ncap_frcap_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 112);ahdlDoSetLineNum ((long) 112);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_936) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 113);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_152))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_152))));(_vnew_896) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 114);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_104) * (_vnew_896))));__tmpStkVar_3 = ((((_pc1_104)) * ((__tmpStkVar_2))));(_qcalc1_656) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 115);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_128) * ((ahdlSqrt(((((((((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_128)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))) * ((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) + ((((((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))) * ((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))))))))))))));(_qcalc2_696) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 116);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_224) * ((ahdlSqrt(((((((((((_vnew_896) - (_pc7_272)))) * ((((_vnew_896) - (_pc7_272))))))) + ((((_pc6_248) * (_pc6_248)))))))))))));__tmpStkVar_5 = ((((_pc5_224)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_vnew_896)) - ((_pc7_272)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_248))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_vnew_896)) - ((_pc7_272)))) * ((((_vnew_896)) - ((_pc7_272)))))))) + (((((_pc6_248) * (_pc6_248))))))))))))))));(_qcalc3_736) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 117);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((((((((((((((_pcg_296) * (_p_pcvd_152)))) * (((__INT_TO_DBL((1L)) - (_pfrac_c_320))))))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_656) + (_qcalc2_696)))) - (_qcalc3_736))))))), __INT_TO_DBL((2L)))));__tmpStkVar_6 = ((__FLOAT_DIV((((((((((((((_pcg_296)) * ((_p_pcvd_152))))) * ((((__INT_TO_DBL((1L))) - ((_pfrac_c_320)))))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_344)) * ((_deltemp_416))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5))))))), __INT_TO_DBL((2L)))));(_qcalc_616) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 118);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcf1_80) * (_vnew_896))));__tmpStkVar_7 = ((((_pcf1_80)) * ((__tmpStkVar_2))));(_qfrcalc1_536) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 119);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_pcof_56) * (_p_pcvd_152)))) * (_qfrcalc1_536))));__tmpStkVar_8 = (((((((_pcof_56)) * ((_p_pcvd_152))))) * ((__tmpStkVar_7))));(_qfrcalc_576) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 120);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((((((((((((((((_pccor_464) + (_pnear_m1_c_440)))) + (_pcm1_cap_488)))) + (_pc_ca_cap_512)))) * (_vnew_896)))) * (_p_pcvd_152)))), __INT_TO_DBL((2L)))));__tmpStkVar_9 = ((__FLOAT_DIV(((((((((((((((((_pccor_464)) + ((_pnear_m1_c_440))))) + ((_pcm1_cap_488))))) + ((_pc_ca_cap_512))))) * ((__tmpStkVar_2))))) * ((_p_pcvd_152)))), __INT_TO_DBL((2L)))));(_qnear_856) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 121);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((((((2.00000000000000000000e+00)) * (((((((_qcalc_616) + (_qfrcalc_576)))) + (_qnear_856))))))) * (_m_32))));__tmpStkVar_10 = ((((((((2.00000000000000000000e+00))) * ((((((((__tmpStkVar_6)) + ((__tmpStkVar_8))))) + ((__tmpStkVar_9)))))))) * ((_m_32))));(_qtot_816) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 123);    return __msgSeverity__;
} /** end of ncap_frcap_DcFuncDerLoad **/

int ncap_frcap_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 112);ahdlDoSetLineNum ((long) 112);(_testvolt_936) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 113);(_vnew_896) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_152))));ahdlDoSetLineNum ((long) 114);(_qcalc1_656) = ((((_pc1_104) * (_vnew_896))));ahdlDoSetLineNum ((long) 115);(_qcalc2_696) = ((((_pc2_128) * ((ahdlSqrt(((((((((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));ahdlDoSetLineNum ((long) 116);(_qcalc3_736) = ((((_pc5_224) * ((ahdlSqrt(((((((((((_vnew_896) - (_pc7_272)))) * ((((_vnew_896) - (_pc7_272))))))) + ((((_pc6_248) * (_pc6_248)))))))))))));ahdlDoSetLineNum ((long) 117);(_qcalc_616) = ((__FLOAT_DIV((((((((((((((_pcg_296) * (_p_pcvd_152)))) * (((__INT_TO_DBL((1L)) - (_pfrac_c_320))))))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_656) + (_qcalc2_696)))) - (_qcalc3_736))))))), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 118);(_qfrcalc1_536) = ((((_pcf1_80) * (_vnew_896))));ahdlDoSetLineNum ((long) 119);(_qfrcalc_576) = (((((((_pcof_56) * (_p_pcvd_152)))) * (_qfrcalc1_536))));ahdlDoSetLineNum ((long) 120);(_qnear_856) = ((__FLOAT_DIV(((((((((((((((((_pccor_464) + (_pnear_m1_c_440)))) + (_pcm1_cap_488)))) + (_pc_ca_cap_512)))) * (_vnew_896)))) * (_p_pcvd_152)))), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 121);(_qtot_816) = ((((((((2.00000000000000000000e+00)) * (((((((_qcalc_616) + (_qfrcalc_576)))) + (_qnear_856))))))) * (_m_32))));}ahdlDoSetLineNum ((long) 123);    return __msgSeverity__;
} /** end of ncap_frcap_DcFuncLoad **/

int ncap_frcap_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_992 = 0.0;
_Dynamic_d_by_dv_vp_vn_976 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 112);ahdlDoSetLineNum ((long) 112);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_936) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 113);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_152))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_152))));(_vnew_896) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 114);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_104) * (_vnew_896))));__tmpStkVar_3 = ((((_pc1_104)) * ((__tmpStkVar_2))));(_qcalc1_656) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 115);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_128) * ((ahdlSqrt(((((((((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_128)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))) * ((((_vnew_896)) - (((((_pc4_200)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_392)) * ((_deltemp_416))))))))))))))))) + ((((((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))) * ((((_pc3_176)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_368)) * ((_deltemp_416)))))))))))))))))))))))));(_qcalc2_696) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 116);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_224) * ((ahdlSqrt(((((((((((_vnew_896) - (_pc7_272)))) * ((((_vnew_896) - (_pc7_272))))))) + ((((_pc6_248) * (_pc6_248)))))))))))));__tmpStkVar_5 = ((((_pc5_224)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_vnew_896)) - ((_pc7_272)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_248))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_vnew_896)) - ((_pc7_272)))) * ((((_vnew_896)) - ((_pc7_272)))))))) + (((((_pc6_248) * (_pc6_248))))))))))))))));(_qcalc3_736) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 117);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((((((((((((((_pcg_296) * (_p_pcvd_152)))) * (((__INT_TO_DBL((1L)) - (_pfrac_c_320))))))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_656) + (_qcalc2_696)))) - (_qcalc3_736))))))), __INT_TO_DBL((2L)))));__tmpStkVar_6 = ((__FLOAT_DIV((((((((((((((_pcg_296)) * ((_p_pcvd_152))))) * ((((__INT_TO_DBL((1L))) - ((_pfrac_c_320)))))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_344)) * ((_deltemp_416))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5))))))), __INT_TO_DBL((2L)))));(_qcalc_616) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 118);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcf1_80) * (_vnew_896))));__tmpStkVar_7 = ((((_pcf1_80)) * ((__tmpStkVar_2))));(_qfrcalc1_536) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 119);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_pcof_56) * (_p_pcvd_152)))) * (_qfrcalc1_536))));__tmpStkVar_8 = (((((((_pcof_56)) * ((_p_pcvd_152))))) * ((__tmpStkVar_7))));(_qfrcalc_576) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 120);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((((((((((((((((_pccor_464) + (_pnear_m1_c_440)))) + (_pcm1_cap_488)))) + (_pc_ca_cap_512)))) * (_vnew_896)))) * (_p_pcvd_152)))), __INT_TO_DBL((2L)))));__tmpStkVar_9 = ((__FLOAT_DIV(((((((((((((((((_pccor_464)) + ((_pnear_m1_c_440))))) + ((_pcm1_cap_488))))) + ((_pc_ca_cap_512))))) * ((__tmpStkVar_2))))) * ((_p_pcvd_152)))), __INT_TO_DBL((2L)))));(_qnear_856) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 121);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((((((2.00000000000000000000e+00)) * (((((((_qcalc_616) + (_qfrcalc_576)))) + (_qnear_856))))))) * (_m_32))));__tmpStkVar_10 = ((((((((2.00000000000000000000e+00))) * ((((((((__tmpStkVar_6)) + ((__tmpStkVar_8))))) + ((__tmpStkVar_9)))))))) * ((_m_32))));(_qtot_816) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 122);(_I_Dynamic_vp_vn_992) += (_qtot_816);_Dynamic_d_by_dv_vp_vn_976 += (__tmpStkVar_10);}ahdlDoSetLineNum ((long) 123);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_992;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_992;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_992);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_992);
   }

      ahdlInterAddDynamicQuartet(*(void**)(instData + 968),_Dynamic_d_by_dv_vp_vn_976);
    return __msgSeverity__;
} /** end of ncap_frcap_TranFuncDerLoad **/

int ncap_frcap_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_992 = 0.0;
_Dynamic_d_by_dv_vp_vn_976 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 112);ahdlDoSetLineNum ((long) 112);(_testvolt_936) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 113);(_vnew_896) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_152))));ahdlDoSetLineNum ((long) 114);(_qcalc1_656) = ((((_pc1_104) * (_vnew_896))));ahdlDoSetLineNum ((long) 115);(_qcalc2_696) = ((((_pc2_128) * ((ahdlSqrt(((((((((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416))))))))))))) * ((((_vnew_896) - ((((_pc4_200) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_392) * (_deltemp_416)))))))))))))))) + (((((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416)))))))))) * ((((_pc3_176) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_368) * (_deltemp_416))))))))))))))))))))));ahdlDoSetLineNum ((long) 116);(_qcalc3_736) = ((((_pc5_224) * ((ahdlSqrt(((((((((((_vnew_896) - (_pc7_272)))) * ((((_vnew_896) - (_pc7_272))))))) + ((((_pc6_248) * (_pc6_248)))))))))))));ahdlDoSetLineNum ((long) 117);(_qcalc_616) = ((__FLOAT_DIV((((((((((((((_pcg_296) * (_p_pcvd_152)))) * (((__INT_TO_DBL((1L)) - (_pfrac_c_320))))))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_344) * (_deltemp_416)))))))))) * (((((((_qcalc1_656) + (_qcalc2_696)))) - (_qcalc3_736))))))), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 118);(_qfrcalc1_536) = ((((_pcf1_80) * (_vnew_896))));ahdlDoSetLineNum ((long) 119);(_qfrcalc_576) = (((((((_pcof_56) * (_p_pcvd_152)))) * (_qfrcalc1_536))));ahdlDoSetLineNum ((long) 120);(_qnear_856) = ((__FLOAT_DIV(((((((((((((((((_pccor_464) + (_pnear_m1_c_440)))) + (_pcm1_cap_488)))) + (_pc_ca_cap_512)))) * (_vnew_896)))) * (_p_pcvd_152)))), __INT_TO_DBL((2L)))));ahdlDoSetLineNum ((long) 121);(_qtot_816) = ((((((((2.00000000000000000000e+00)) * (((((((_qcalc_616) + (_qfrcalc_576)))) + (_qnear_856))))))) * (_m_32))));ahdlDoSetLineNum ((long) 122);(_I_Dynamic_vp_vn_992) += (_qtot_816);}ahdlDoSetLineNum ((long) 123);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_992;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_992;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_992);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_992);
   }

    return __msgSeverity__;
} /** end of ncap_frcap_TranFuncLoad **/

int ncap_frcap_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of ncap_frcap_NoiseLoadBiasDep **/

