/** 2443715016 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef BSOURCE_1_INST_STATIC_H
#define BSOURCE_1_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_bs_p1_bs_p2_944	(*((double *) &instData [944]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_bs_p1_bs_p2_936	(*((double *) &instData [936]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dflicker_noise_928	(*((double *) &instData [928]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dwhite_noise_904	(*((double *) &instData [904]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_bs_p1_bs_p2_888	(*((double *) &instData [888]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_bs_p3_bs_p4_872	(*((double *) &instData [872]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_bs_p5_bs_p4_856	(*((double *) &instData [856]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_bs_p3_bs_p5_840	(*((double *) &instData [840]))	/* Branch Load Group : Size = 8 bytes. */
#define _bs_par_10_800	(*((double *) &instData [800]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_9_776	(*((double *) &instData [776]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_8_752	(*((double *) &instData [752]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_7_728	(*((double *) &instData [728]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_6_704	(*((double *) &instData [704]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_5_680	(*((double *) &instData [680]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_4_656	(*((double *) &instData [656]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_3_632	(*((double *) &instData [632]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_2_608	(*((double *) &instData [608]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_1_584	(*((double *) &instData [584]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_par_0_560	(*((double *) &instData [560]))	/* VT_REAL : Size = 8 bytes. */
#define _i_520	(*((double *) &instData [520]))	/* VT_REAL : Size = 8 bytes. */
#define _v_480	(*((double *) &instData [480]))	/* VT_REAL : Size = 8 bytes. */
#define _res_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _w_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _l_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _wdexp_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _ldexp_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _fexp_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _af_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _kf_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _Txm_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _m_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _Tx_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _T_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _trise_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _tc2_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _tc1_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _tnom_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _temp_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _bs_p5_44	(*((long *) &instData [44]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_p4_36	(*((long *) &instData [36]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_p3_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_p2_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _bs_p1_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* BSOURCE_1_INST_STATIC_H */
