/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include "ahdlcmi.h"

int ahdlBsourceInterfaceVersion() {
   return 1; /* Only used when version >= spectre's BsourceInterfaceVersion */
}

extern int pcap_cap_DcFuncDerLoad(int, char*, char*, char**);
extern int pcap_cap_DcFuncLoad(int, char*, char*, char**);
extern int pcap_cap_TranFuncDerLoad(int, char*, char*, char**);
extern int pcap_cap_TranFuncLoad(int, char*, char*, char**);
extern int pcap_cap_NoiseLoadBiasDep(int, char*, char*, char**);

int pcap_cap_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        pcap_cap_DcFuncDerLoad,  
                        pcap_cap_DcFuncLoad,     
                        pcap_cap_TranFuncDerLoad,
                        pcap_cap_TranFuncLoad,   
                        pcap_cap_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
extern int pcap_cur_DcFuncDerLoad(int, char*, char*, char**);
extern int pcap_cur_DcFuncLoad(int, char*, char*, char**);
extern int pcap_cur_TranFuncDerLoad(int, char*, char*, char**);
extern int pcap_cur_TranFuncLoad(int, char*, char*, char**);
extern int pcap_cur_NoiseLoadBiasDep(int, char*, char*, char**);

int pcap_cur_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        pcap_cur_DcFuncDerLoad,  
                        pcap_cur_DcFuncLoad,     
                        pcap_cur_TranFuncDerLoad,
                        pcap_cur_TranFuncLoad,   
                        pcap_cur_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
extern int pcap_res2_DcFuncDerLoad(int, char*, char*, char**);
extern int pcap_res2_DcFuncLoad(int, char*, char*, char**);
extern int pcap_res2_TranFuncDerLoad(int, char*, char*, char**);
extern int pcap_res2_TranFuncLoad(int, char*, char*, char**);
extern int pcap_res2_NoiseLoadBiasDep(int, char*, char*, char**);

int pcap_res2_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        pcap_res2_DcFuncDerLoad,  
                        pcap_res2_DcFuncLoad,     
                        pcap_res2_TranFuncDerLoad,
                        pcap_res2_TranFuncLoad,   
                        pcap_res2_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
