/** 385998910 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "pcap_cap_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int pcap_cap_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 51);ahdlDoSetLineNum ((long) 51);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_648) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 52);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_608) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 53);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_608))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_408) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 54);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_608) - (_pc4_152)))) * ((((_v1_608) - (_pc4_152))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_608)) - ((_pc4_152)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_608)) - ((_pc4_152)))) * ((((_v1_608)) - ((_pc4_152)))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))))))))))))))))));(_qcalc2_448) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 55);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_608) - (_pc7_224)))) * ((((_v1_608) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_608)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_608)) - ((_pc7_224)))) * ((((_v1_608)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_488) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 56);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_pcg_272) * (_p_pcvd_104)))) * (((((((_qcalc1_408) + (_qcalc2_448)))) - (_qcalc3_488)))))));__tmpStkVar_6 = (((((((_pcg_272)) * ((_p_pcvd_104))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_528) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 57);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((__INT_TO_DBL((2L)) * (_p_pcvd_104)))) * (_pcof_344)))) * ((((_pcf1_248) * (_v1_608)))))));__tmpStkVar_7 = (((((((((__INT_TO_DBL((2L))) * ((_p_pcvd_104))))) * ((_pcof_344))))) * (((((_pcf1_248)) * ((__tmpStkVar_2)))))));(_qcalfrl_568) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 58);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_528) + (_qcalfrl_568)))) * (_m_32))));__tmpStkVar_8 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_7))))) * ((_m_32))));(_qcalc_368) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 60);    return __msgSeverity__;
} /** end of pcap_cap_DcFuncDerLoad **/

int pcap_cap_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 51);ahdlDoSetLineNum ((long) 51);(_testvolt_648) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 52);(_v1_608) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 53);(_qcalc1_408) = ((((_pc1_56) * (_v1_608))));ahdlDoSetLineNum ((long) 54);(_qcalc2_448) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_608) - (_pc4_152)))) * ((((_v1_608) - (_pc4_152))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320))))))))))))))))))))));ahdlDoSetLineNum ((long) 55);(_qcalc3_488) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_608) - (_pc7_224)))) * ((((_v1_608) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 56);(_qcalcg_528) = (((((((_pcg_272) * (_p_pcvd_104)))) * (((((((_qcalc1_408) + (_qcalc2_448)))) - (_qcalc3_488)))))));ahdlDoSetLineNum ((long) 57);(_qcalfrl_568) = (((((((((__INT_TO_DBL((2L)) * (_p_pcvd_104)))) * (_pcof_344)))) * ((((_pcf1_248) * (_v1_608)))))));ahdlDoSetLineNum ((long) 58);(_qcalc_368) = (((((((_qcalcg_528) + (_qcalfrl_568)))) * (_m_32))));}ahdlDoSetLineNum ((long) 60);    return __msgSeverity__;
} /** end of pcap_cap_DcFuncLoad **/

int pcap_cap_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_704 = 0.0;
_Dynamic_d_by_dv_vp_vn_688 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 51);ahdlDoSetLineNum ((long) 51);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_648) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 52);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_608) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 53);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_608))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_408) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 54);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_608) - (_pc4_152)))) * ((((_v1_608) - (_pc4_152))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_608)) - ((_pc4_152)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_608)) - ((_pc4_152)))) * ((((_v1_608)) - ((_pc4_152)))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pcatcr_296)) * ((_deltemp_320)))))))))))))))))))))))));(_qcalc2_448) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 55);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_608) - (_pc7_224)))) * ((((_v1_608) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_608)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_608)) - ((_pc7_224)))) * ((((_v1_608)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_488) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 56);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_pcg_272) * (_p_pcvd_104)))) * (((((((_qcalc1_408) + (_qcalc2_448)))) - (_qcalc3_488)))))));__tmpStkVar_6 = (((((((_pcg_272)) * ((_p_pcvd_104))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_528) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 57);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((__INT_TO_DBL((2L)) * (_p_pcvd_104)))) * (_pcof_344)))) * ((((_pcf1_248) * (_v1_608)))))));__tmpStkVar_7 = (((((((((__INT_TO_DBL((2L))) * ((_p_pcvd_104))))) * ((_pcof_344))))) * (((((_pcf1_248)) * ((__tmpStkVar_2)))))));(_qcalfrl_568) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 58);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_528) + (_qcalfrl_568)))) * (_m_32))));__tmpStkVar_8 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_7))))) * ((_m_32))));(_qcalc_368) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 59);(_I_Dynamic_vp_vn_704) += (_qcalc_368);_Dynamic_d_by_dv_vp_vn_688 += (__tmpStkVar_8);}ahdlDoSetLineNum ((long) 60);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_704;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_704;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_704);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_704);
   }

      ahdlInterAddDynamicQuartet(*(void**)(instData + 680),_Dynamic_d_by_dv_vp_vn_688);
    return __msgSeverity__;
} /** end of pcap_cap_TranFuncDerLoad **/

int pcap_cap_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_704 = 0.0;
_Dynamic_d_by_dv_vp_vn_688 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 51);ahdlDoSetLineNum ((long) 51);(_testvolt_648) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 52);(_v1_608) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 53);(_qcalc1_408) = ((((_pc1_56) * (_v1_608))));ahdlDoSetLineNum ((long) 54);(_qcalc2_448) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_608) - (_pc4_152)))) * ((((_v1_608) - (_pc4_152))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pcatcr_296) * (_deltemp_320))))))))))))))))))))));ahdlDoSetLineNum ((long) 55);(_qcalc3_488) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_608) - (_pc7_224)))) * ((((_v1_608) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 56);(_qcalcg_528) = (((((((_pcg_272) * (_p_pcvd_104)))) * (((((((_qcalc1_408) + (_qcalc2_448)))) - (_qcalc3_488)))))));ahdlDoSetLineNum ((long) 57);(_qcalfrl_568) = (((((((((__INT_TO_DBL((2L)) * (_p_pcvd_104)))) * (_pcof_344)))) * ((((_pcf1_248) * (_v1_608)))))));ahdlDoSetLineNum ((long) 58);(_qcalc_368) = (((((((_qcalcg_528) + (_qcalfrl_568)))) * (_m_32))));ahdlDoSetLineNum ((long) 59);(_I_Dynamic_vp_vn_704) += (_qcalc_368);}ahdlDoSetLineNum ((long) 60);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_704;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_704;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_704);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_704);
   }

    return __msgSeverity__;
} /** end of pcap_cap_TranFuncLoad **/

int pcap_cap_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of pcap_cap_NoiseLoadBiasDep **/

