/** 1311323788 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "pcap_res2_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int pcap_res2_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v1_v6_560 = 0.0;
_Static_d_by_dv_v2_v1_536 = 0.0;
_Static_d_by_dv_v1_v6_552 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 124);ahdlDoSetLineNum ((long) 124);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_12))), (_p_pcvd_64))));__tmpStkVar_1 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_64))));(_vsub_496) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 125);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pwr1_88) - ((__FLOAT_DIV(((((_pwr2_112) * ((((_vsub_496) - (_pwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pwr4_160)))) * ((((_vsub_496) - (_pwr4_160))))))) + ((((_pwr3_136) * (_pwr3_136))))))))))))))));__tmpStkVar_2 = (((-(__FLOAT_DIV(((((((((((_pwr2_112)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_496)) - ((_pwr4_160)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))))))) * (((((_pwr2_112)) * (((((_vsub_496)) - ((_pwr4_160))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))), ((2.00000000000000000000e+00))))))))));(_p_ebodr_416) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 126);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_496) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pendr4_256)))) * ((((_vsub_496) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));__tmpStkVar_3 = (((-(__FLOAT_DIV(((((((((((_pendr2_208)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_496)) - ((_pendr4_256)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) * (((((_pendr2_208)) * (((((_vsub_496)) - ((_pendr4_256))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))), ((2.00000000000000000000e+00))))))))));(_p_eendr_456) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 127);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((((((((((_p_ebodr_416) * (_prpw_280)))) + ((((_p_eendr_456) * (_pendr_304))))))) + ((((_pinc_m1rf_352) * (_pr_rx_328))))))), (_m_40))));__tmpStkVar_4 = ((__FLOAT_DIV((((((((__tmpStkVar_2)) * ((_prpw_280))))) + (((((__tmpStkVar_3)) * ((_pendr_304))))))), (_m_40))));(_res_376) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 129);(_I_Static_v1_v6_560) += (__FLOAT_DIV(((getAcrossSolution2(_v1_12, _v6_20))), ((_res_376))));_Static_d_by_dv_v2_v1_536 += ((__FLOAT_DIV((((-(((__tmpStkVar_4)) * (((getAcrossSolution2(_v1_12, _v6_20)))))))), ((ahdlPow(((_res_376)), ((2.00000000000000000000e+00))))))));_Static_d_by_dv_v1_v6_552 += ((__FLOAT_DIV(((1.00000000000000000000e+00)), ((_res_376)))));}ahdlDoSetLineNum ((long) 131);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v1_12] -= _I_Static_v1_v6_560;
      ahdlStaticRHS[_v6_20] += _I_Static_v1_v6_560;
      ahdlStaticRHS_AbsSum[_v1_12] += ABS(_I_Static_v1_v6_560);
      ahdlStaticRHS_AbsSum[_v6_20] += ABS(_I_Static_v1_v6_560);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 528),_Static_d_by_dv_v2_v1_536);
      ahdlInterAddStaticQuartet(*(void**)(instData + 544),_Static_d_by_dv_v1_v6_552);
    return __msgSeverity__;
} /** end of pcap_res2_DcFuncDerLoad **/

int pcap_res2_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v1_v6_560 = 0.0;
_Static_d_by_dv_v2_v1_536 = 0.0;
_Static_d_by_dv_v1_v6_552 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 124);ahdlDoSetLineNum ((long) 124);(_vsub_496) = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_12))), (_p_pcvd_64))));ahdlDoSetLineNum ((long) 125);(_p_ebodr_416) = ((((_pwr1_88) - ((__FLOAT_DIV(((((_pwr2_112) * ((((_vsub_496) - (_pwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pwr4_160)))) * ((((_vsub_496) - (_pwr4_160))))))) + ((((_pwr3_136) * (_pwr3_136))))))))))))))));ahdlDoSetLineNum ((long) 126);(_p_eendr_456) = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_496) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pendr4_256)))) * ((((_vsub_496) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));ahdlDoSetLineNum ((long) 127);(_res_376) = ((__FLOAT_DIV(((((((((((_p_ebodr_416) * (_prpw_280)))) + ((((_p_eendr_456) * (_pendr_304))))))) + ((((_pinc_m1rf_352) * (_pr_rx_328))))))), (_m_40))));ahdlDoSetLineNum ((long) 129);(_I_Static_v1_v6_560) += (__FLOAT_DIV(((getAcrossSolution2(_v1_12, _v6_20))), ((_res_376))));}ahdlDoSetLineNum ((long) 131);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v1_12] -= _I_Static_v1_v6_560;
      ahdlStaticRHS[_v6_20] += _I_Static_v1_v6_560;
      ahdlStaticRHS_AbsSum[_v1_12] += ABS(_I_Static_v1_v6_560);
      ahdlStaticRHS_AbsSum[_v6_20] += ABS(_I_Static_v1_v6_560);
   }

    return __msgSeverity__;
} /** end of pcap_res2_DcFuncLoad **/

int pcap_res2_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v1_v6_560 = 0.0;
_Static_d_by_dv_v2_v1_536 = 0.0;
_Static_d_by_dv_v1_v6_552 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 124);ahdlDoSetLineNum ((long) 124);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_12))), (_p_pcvd_64))));__tmpStkVar_1 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_64))));(_vsub_496) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 125);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pwr1_88) - ((__FLOAT_DIV(((((_pwr2_112) * ((((_vsub_496) - (_pwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pwr4_160)))) * ((((_vsub_496) - (_pwr4_160))))))) + ((((_pwr3_136) * (_pwr3_136))))))))))))))));__tmpStkVar_2 = (((-(__FLOAT_DIV(((((((((((_pwr2_112)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_496)) - ((_pwr4_160)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))))))) * (((((_pwr2_112)) * (((((_vsub_496)) - ((_pwr4_160))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_496)) - ((_pwr4_160)))) * ((((_vsub_496)) - ((_pwr4_160)))))))) + (((((_pwr3_136)) * ((_pwr3_136)))))))))), ((2.00000000000000000000e+00))))))))));(_p_ebodr_416) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 126);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_496) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pendr4_256)))) * ((((_vsub_496) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));__tmpStkVar_3 = (((-(__FLOAT_DIV(((((((((((_pendr2_208)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_496)) - ((_pendr4_256)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) * (((((_pendr2_208)) * (((((_vsub_496)) - ((_pendr4_256))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_496)) - ((_pendr4_256)))) * ((((_vsub_496)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))), ((2.00000000000000000000e+00))))))))));(_p_eendr_456) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 127);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((((((((((_p_ebodr_416) * (_prpw_280)))) + ((((_p_eendr_456) * (_pendr_304))))))) + ((((_pinc_m1rf_352) * (_pr_rx_328))))))), (_m_40))));__tmpStkVar_4 = ((__FLOAT_DIV((((((((__tmpStkVar_2)) * ((_prpw_280))))) + (((((__tmpStkVar_3)) * ((_pendr_304))))))), (_m_40))));(_res_376) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 129);(_I_Static_v1_v6_560) += (__FLOAT_DIV(((getAcrossSolution2(_v1_12, _v6_20))), ((_res_376))));_Static_d_by_dv_v2_v1_536 += ((__FLOAT_DIV((((-(((__tmpStkVar_4)) * (((getAcrossSolution2(_v1_12, _v6_20)))))))), ((ahdlPow(((_res_376)), ((2.00000000000000000000e+00))))))));_Static_d_by_dv_v1_v6_552 += ((__FLOAT_DIV(((1.00000000000000000000e+00)), ((_res_376)))));}ahdlDoSetLineNum ((long) 131);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v1_12] -= _I_Static_v1_v6_560;
      ahdlStaticRHS[_v6_20] += _I_Static_v1_v6_560;
      ahdlStaticRHS_AbsSum[_v1_12] += ABS(_I_Static_v1_v6_560);
      ahdlStaticRHS_AbsSum[_v6_20] += ABS(_I_Static_v1_v6_560);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 528),_Static_d_by_dv_v2_v1_536);
      ahdlInterAddStaticQuartet(*(void**)(instData + 544),_Static_d_by_dv_v1_v6_552);
    return __msgSeverity__;
} /** end of pcap_res2_TranFuncDerLoad **/

int pcap_res2_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v1_v6_560 = 0.0;
_Static_d_by_dv_v2_v1_536 = 0.0;
_Static_d_by_dv_v1_v6_552 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 124);ahdlDoSetLineNum ((long) 124);(_vsub_496) = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_12))), (_p_pcvd_64))));ahdlDoSetLineNum ((long) 125);(_p_ebodr_416) = ((((_pwr1_88) - ((__FLOAT_DIV(((((_pwr2_112) * ((((_vsub_496) - (_pwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pwr4_160)))) * ((((_vsub_496) - (_pwr4_160))))))) + ((((_pwr3_136) * (_pwr3_136))))))))))))))));ahdlDoSetLineNum ((long) 126);(_p_eendr_456) = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_496) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_496) - (_pendr4_256)))) * ((((_vsub_496) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));ahdlDoSetLineNum ((long) 127);(_res_376) = ((__FLOAT_DIV(((((((((((_p_ebodr_416) * (_prpw_280)))) + ((((_p_eendr_456) * (_pendr_304))))))) + ((((_pinc_m1rf_352) * (_pr_rx_328))))))), (_m_40))));ahdlDoSetLineNum ((long) 129);(_I_Static_v1_v6_560) += (__FLOAT_DIV(((getAcrossSolution2(_v1_12, _v6_20))), ((_res_376))));}ahdlDoSetLineNum ((long) 131);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v1_12] -= _I_Static_v1_v6_560;
      ahdlStaticRHS[_v6_20] += _I_Static_v1_v6_560;
      ahdlStaticRHS_AbsSum[_v1_12] += ABS(_I_Static_v1_v6_560);
      ahdlStaticRHS_AbsSum[_v6_20] += ABS(_I_Static_v1_v6_560);
   }

    return __msgSeverity__;
} /** end of pcap_res2_TranFuncLoad **/

int pcap_res2_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of pcap_res2_NoiseLoadBiasDep **/

