/** 3524499502 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef PCAP_RES2_INST_STATIC_H
#define PCAP_RES2_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_v1_v6_568	(*((double *) &instData [568]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_v1_v6_560	(*((double *) &instData [560]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_v1_v6_552	(*((double *) &instData [552]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_v2_v1_536	(*((double *) &instData [536]))	/* Branch Load Group : Size = 8 bytes. */
#define _vsub_496	(*((double *) &instData [496]))	/* VT_REAL : Size = 8 bytes. */
#define _p_eendr_456	(*((double *) &instData [456]))	/* VT_REAL : Size = 8 bytes. */
#define _p_ebodr_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _res_376	(*((double *) &instData [376]))	/* VT_REAL : Size = 8 bytes. */
#define _pinc_m1rf_352	(*((double *) &instData [352]))	/* VT_REAL : Size = 8 bytes. */
#define _pr_rx_328	(*((double *) &instData [328]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr_304	(*((double *) &instData [304]))	/* VT_REAL : Size = 8 bytes. */
#define _prpw_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr4_256	(*((double *) &instData [256]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr3_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr2_208	(*((double *) &instData [208]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr1_184	(*((double *) &instData [184]))	/* VT_REAL : Size = 8 bytes. */
#define _pwr4_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _pwr3_136	(*((double *) &instData [136]))	/* VT_REAL : Size = 8 bytes. */
#define _pwr2_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _pwr1_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _m_40	(*((double *) &instData [40]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [40]))	/* VT_REAL : Size = 8 bytes. */
#define _v2_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _v6_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _v1_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* PCAP_RES2_INST_STATIC_H */
