python3 scripts/plot.py SL_nand2 test1
python3 scripts/plot.py SL_nand2 test2
python3 scripts/plot.py SL_nand2 test3
python3 scripts/plot.py SL_nand2 test4
python3 scripts/plot.py SL_nand2 test5
python3 scripts/plot.py SL_nand2 test6
python3 scripts/plot.py SL_nand2 test7
python3 scripts/plot.py SL_nand2 test8
python3 scripts/plot.py SL_nand2 test9
python3 scripts/plot.py SL_nand2 test10
python3 scripts/plot.py SL_nand2 test11
python3 scripts/plot.py SL_nand2 test12
python3 scripts/plot.py SL_nand2 test13
python3 scripts/plot.py SL_nand2 test14
python3 scripts/plot.py SL_nand2 test15
python3 scripts/plot.py SL_nand2 test16