/** 3925697643 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "dgncap_cap_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int dgncap_cap_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 72);ahdlDoSetLineNum ((long) 72);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_1088) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 73);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_1048) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 74);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_1048))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_648) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 75);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560))))))))))))) * ((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))) * ((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))))))))))))))))));(_qcalc2_688) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 76);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_1048) - (_pc7_224)))) * ((((_v1_1048) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - ((_pc7_224)))) * ((((_v1_1048)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_728) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 77);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((((_pcg_416) * (_p_pcvd_104)))) * (_pfrac_c_440)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_488) * (_deltemp_560)))))))))) * (((((((_qcalc1_648) + (_qcalc2_688)))) - (_qcalc3_728)))))));__tmpStkVar_6 = (((((((((((((_pcg_416)) * ((_p_pcvd_104))))) * ((_pfrac_c_440))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_488)) * ((_deltemp_560))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_848) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 78);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl1_320) * (_v1_1048))));__tmpStkVar_7 = ((((_pcfl1_320)) * ((__tmpStkVar_2))));(_qfrgl1_888) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 79);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl2_344) * ((ahdlSqrt(((((((((((_v1_1048) - (_pcfl4_392)))) * ((((_v1_1048) - (_pcfl4_392))))))) + ((((_pcfl3_368) * (_pcfl3_368)))))))))))));__tmpStkVar_8 = ((((_pcfl2_344)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - ((_pcfl4_392)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pcfl3_368))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - ((_pcfl4_392)))) * ((((_v1_1048)) - ((_pcfl4_392)))))))) + (((((_pcfl3_368) * (_pcfl3_368))))))))))))))));(_qfrgl2_928) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 80);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_584)))) * ((((_qfrgl1_888) + (_qfrgl2_928)))))));__tmpStkVar_9 = (((((((((((2.00000000000000000000e+00))) * ((_p_pcvd_104))))) * ((_pcofl_584))))) * (((((__tmpStkVar_7)) + ((__tmpStkVar_8)))))));(_qcalfrl_968) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 81);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_848) + (_qcalfrl_968)))) * (_m_32))));__tmpStkVar_10 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_9))))) * ((_m_32))));(_qcalc_608) = __tempValueResultStatic;}}ahdlDoSetLineNum ((long) 83);    return __msgSeverity__;
} /** end of dgncap_cap_DcFuncDerLoad **/

int dgncap_cap_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */
/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 72);ahdlDoSetLineNum ((long) 72);(_testvolt_1088) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 73);(_v1_1048) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 74);(_qcalc1_648) = ((((_pc1_56) * (_v1_1048))));ahdlDoSetLineNum ((long) 75);(_qcalc2_688) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560))))))))))))) * ((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560))))))))))))))))))))));ahdlDoSetLineNum ((long) 76);(_qcalc3_728) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_1048) - (_pc7_224)))) * ((((_v1_1048) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 77);(_qcalcg_848) = (((((((((((((_pcg_416) * (_p_pcvd_104)))) * (_pfrac_c_440)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_488) * (_deltemp_560)))))))))) * (((((((_qcalc1_648) + (_qcalc2_688)))) - (_qcalc3_728)))))));ahdlDoSetLineNum ((long) 78);(_qfrgl1_888) = ((((_pcfl1_320) * (_v1_1048))));ahdlDoSetLineNum ((long) 79);(_qfrgl2_928) = ((((_pcfl2_344) * ((ahdlSqrt(((((((((((_v1_1048) - (_pcfl4_392)))) * ((((_v1_1048) - (_pcfl4_392))))))) + ((((_pcfl3_368) * (_pcfl3_368)))))))))))));ahdlDoSetLineNum ((long) 80);(_qcalfrl_968) = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_584)))) * ((((_qfrgl1_888) + (_qfrgl2_928)))))));ahdlDoSetLineNum ((long) 81);(_qcalc_608) = (((((((_qcalcg_848) + (_qcalfrl_968)))) * (_m_32))));}ahdlDoSetLineNum ((long) 83);    return __msgSeverity__;
} /** end of dgncap_cap_DcFuncLoad **/

int dgncap_cap_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_1144 = 0.0;
_Dynamic_d_by_dv_vp_vn_1128 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 72);ahdlDoSetLineNum ((long) 72);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((getAcrossSolution2(_vp_12, _vn_20)));__tmpStkVar_1 = ((1.00000000000000000000e+00));(_testvolt_1088) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 73);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));__tmpStkVar_2 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_104))));(_v1_1048) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 74);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc1_56) * (_v1_1048))));__tmpStkVar_3 = ((((_pc1_56)) * ((__tmpStkVar_2))));(_qcalc1_648) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 75);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560))))))))))))) * ((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560))))))))))))))))))))));__tmpStkVar_4 = ((((_pc2_80)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * (((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))) * ((((_v1_1048)) - (((((_pc4_152)) * ((((__INT_TO_DBL((1L))) + (((((_pc4tc_536)) * ((_deltemp_560))))))))))))))))) + ((((((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))) * ((((_pc3_128)) * ((((__INT_TO_DBL((1L))) + (((((_pc3tc_512)) * ((_deltemp_560)))))))))))))))))))))))));(_qcalc2_688) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 76);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_1048) - (_pc7_224)))) * ((((_v1_1048) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));__tmpStkVar_5 = ((((_pc5_176)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - ((_pc7_224)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pc6_200))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - ((_pc7_224)))) * ((((_v1_1048)) - ((_pc7_224)))))))) + (((((_pc6_200) * (_pc6_200))))))))))))))));(_qcalc3_728) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 77);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((((_pcg_416) * (_p_pcvd_104)))) * (_pfrac_c_440)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_488) * (_deltemp_560)))))))))) * (((((((_qcalc1_648) + (_qcalc2_688)))) - (_qcalc3_728)))))));__tmpStkVar_6 = (((((((((((((_pcg_416)) * ((_p_pcvd_104))))) * ((_pfrac_c_440))))) * ((((__INT_TO_DBL((1L))) + (((((_pc0tc_488)) * ((_deltemp_560))))))))))) * ((((((((__tmpStkVar_3)) + ((__tmpStkVar_4))))) - ((__tmpStkVar_5)))))));(_qcalcg_848) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 78);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl1_320) * (_v1_1048))));__tmpStkVar_7 = ((((_pcfl1_320)) * ((__tmpStkVar_2))));(_qfrgl1_888) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 79);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pcfl2_344) * ((ahdlSqrt(((((((((((_v1_1048) - (_pcfl4_392)))) * ((((_v1_1048) - (_pcfl4_392))))))) + ((((_pcfl3_368) * (_pcfl3_368)))))))))))));__tmpStkVar_8 = ((((_pcfl2_344)) * (((((((((((((__INT_TO_DBL((2L))) * (((((_v1_1048)) - ((_pcfl4_392)))))))) * ((__tmpStkVar_2))))) + (((((((__INT_TO_DBL((2L))) * ((_pcfl3_368))))) * (((0.00000000000000000000e+00))))))))) * (((ahdlSqrtDeriv(((((((((((_v1_1048)) - ((_pcfl4_392)))) * ((((_v1_1048)) - ((_pcfl4_392)))))))) + (((((_pcfl3_368) * (_pcfl3_368))))))))))))))));(_qfrgl2_928) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 80);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_584)))) * ((((_qfrgl1_888) + (_qfrgl2_928)))))));__tmpStkVar_9 = (((((((((((2.00000000000000000000e+00))) * ((_p_pcvd_104))))) * ((_pcofl_584))))) * (((((__tmpStkVar_7)) + ((__tmpStkVar_8)))))));(_qcalfrl_968) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 81);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = (((((((_qcalcg_848) + (_qcalfrl_968)))) * (_m_32))));__tmpStkVar_10 = (((((((__tmpStkVar_6)) + ((__tmpStkVar_9))))) * ((_m_32))));(_qcalc_608) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 82);(_I_Dynamic_vp_vn_1144) += (_qcalc_608);_Dynamic_d_by_dv_vp_vn_1128 += (__tmpStkVar_10);}ahdlDoSetLineNum ((long) 83);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_1144;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_1144;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_1144);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_1144);
   }

      ahdlInterAddDynamicQuartet(*(void**)(instData + 1120),_Dynamic_d_by_dv_vp_vn_1128);
    return __msgSeverity__;
} /** end of dgncap_cap_TranFuncDerLoad **/

int dgncap_cap_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Dynamic_vp_vn_1144 = 0.0;
_Dynamic_d_by_dv_vp_vn_1128 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 72);ahdlDoSetLineNum ((long) 72);(_testvolt_1088) = ((getAcrossSolution2(_vp_12, _vn_20)));ahdlDoSetLineNum ((long) 73);(_v1_1048) = ((__FLOAT_DIV(((getAcrossSolution2(_vp_12, _vn_20))), (_p_pcvd_104))));ahdlDoSetLineNum ((long) 74);(_qcalc1_648) = ((((_pc1_56) * (_v1_1048))));ahdlDoSetLineNum ((long) 75);(_qcalc2_688) = ((((_pc2_80) * ((ahdlSqrt(((((((((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560))))))))))))) * ((((_v1_1048) - ((((_pc4_152) * (((__INT_TO_DBL((1L)) + ((((_pc4tc_536) * (_deltemp_560)))))))))))))))) + (((((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560)))))))))) * ((((_pc3_128) * (((__INT_TO_DBL((1L)) + ((((_pc3tc_512) * (_deltemp_560))))))))))))))))))))));ahdlDoSetLineNum ((long) 76);(_qcalc3_728) = ((((_pc5_176) * ((ahdlSqrt(((((((((((_v1_1048) - (_pc7_224)))) * ((((_v1_1048) - (_pc7_224))))))) + ((((_pc6_200) * (_pc6_200)))))))))))));ahdlDoSetLineNum ((long) 77);(_qcalcg_848) = (((((((((((((_pcg_416) * (_p_pcvd_104)))) * (_pfrac_c_440)))) * (((__INT_TO_DBL((1L)) + ((((_pc0tc_488) * (_deltemp_560)))))))))) * (((((((_qcalc1_648) + (_qcalc2_688)))) - (_qcalc3_728)))))));ahdlDoSetLineNum ((long) 78);(_qfrgl1_888) = ((((_pcfl1_320) * (_v1_1048))));ahdlDoSetLineNum ((long) 79);(_qfrgl2_928) = ((((_pcfl2_344) * ((ahdlSqrt(((((((((((_v1_1048) - (_pcfl4_392)))) * ((((_v1_1048) - (_pcfl4_392))))))) + ((((_pcfl3_368) * (_pcfl3_368)))))))))))));ahdlDoSetLineNum ((long) 80);(_qcalfrl_968) = (((((((((((2.00000000000000000000e+00)) * (_p_pcvd_104)))) * (_pcofl_584)))) * ((((_qfrgl1_888) + (_qfrgl2_928)))))));ahdlDoSetLineNum ((long) 81);(_qcalc_608) = (((((((_qcalcg_848) + (_qcalfrl_968)))) * (_m_32))));ahdlDoSetLineNum ((long) 82);(_I_Dynamic_vp_vn_1144) += (_qcalc_608);}ahdlDoSetLineNum ((long) 83);   if (ahdlWhatsNeeded IS devDynamicFuncNeeded) {
      ahdlDynamicRHS[_vp_12] -= _I_Dynamic_vp_vn_1144;
      ahdlDynamicRHS[_vn_20] += _I_Dynamic_vp_vn_1144;
      ahdlDynamicRHS_AbsSum[_vp_12] += ABS(_I_Dynamic_vp_vn_1144);
      ahdlDynamicRHS_AbsSum[_vn_20] += ABS(_I_Dynamic_vp_vn_1144);
   }

    return __msgSeverity__;
} /** end of dgncap_cap_TranFuncLoad **/

int dgncap_cap_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_10 = 0.0;
double	__tmpStkVar_9 = 0.0;
double	__tmpStkVar_8 = 0.0;
double	__tmpStkVar_7 = 0.0;
double	__tmpStkVar_6 = 0.0;
double	__tmpStkVar_5 = 0.0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of dgncap_cap_NoiseLoadBiasDep **/

