/** 4242313900 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DGNCAP_FRCAP_INST_STATIC_H
#define DGNCAP_FRCAP_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_1304	(*((double *) &instData [1304]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_1296	(*((double *) &instData [1296]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Dynamic_d_by_dv_vp_vn_1288	(*((double *) &instData [1288]))	/* Branch Load Group : Size = 8 bytes. */
#define _testvolt_1248	(*((double *) &instData [1248]))	/* VT_REAL : Size = 8 bytes. */
#define _vnew_1208	(*((double *) &instData [1208]))	/* VT_REAL : Size = 8 bytes. */
#define _qnear_1168	(*((double *) &instData [1168]))	/* VT_REAL : Size = 8 bytes. */
#define _qtot_1128	(*((double *) &instData [1128]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc5_1088	(*((double *) &instData [1088]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc4_1048	(*((double *) &instData [1048]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc3_1008	(*((double *) &instData [1008]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc2_968	(*((double *) &instData [968]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc1_928	(*((double *) &instData [928]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc_888	(*((double *) &instData [888]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc_848	(*((double *) &instData [848]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc3_808	(*((double *) &instData [808]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc2_768	(*((double *) &instData [768]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrcalc1_728	(*((double *) &instData [728]))	/* VT_REAL : Size = 8 bytes. */
#define _pcm1_cap_704	(*((double *) &instData [704]))	/* VT_REAL : Size = 8 bytes. */
#define _pccor_680	(*((double *) &instData [680]))	/* VT_REAL : Size = 8 bytes. */
#define _pnear_m1_c_656	(*((double *) &instData [656]))	/* VT_REAL : Size = 8 bytes. */
#define _deltemp_632	(*((double *) &instData [632]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4tc_608	(*((double *) &instData [608]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3tc_584	(*((double *) &instData [584]))	/* VT_REAL : Size = 8 bytes. */
#define _pc0tc_560	(*((double *) &instData [560]))	/* VT_REAL : Size = 8 bytes. */
#define _pfrac_c_536	(*((double *) &instData [536]))	/* VT_REAL : Size = 8 bytes. */
#define _pcg_512	(*((double *) &instData [512]))	/* VT_REAL : Size = 8 bytes. */
#define _pc10_488	(*((double *) &instData [488]))	/* VT_REAL : Size = 8 bytes. */
#define _pc9_464	(*((double *) &instData [464]))	/* VT_REAL : Size = 8 bytes. */
#define _pc8_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _pc7_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _pc6_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _pc5_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _pc2_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _pc1_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf7_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf6_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf5_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf4_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf3_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf2_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _pcf1_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _pcof_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DGNCAP_FRCAP_INST_STATIC_H */
