/** 4002960018 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include "dgncap_res1_inst_static.h"

static long   __BITWISE_LOGIC_OP_TEMP_VAR__;int dgncap_res1_DcFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v5_v1_512 = 0.0;
_Static_d_by_dv_v2_v1_488 = 0.0;
_Static_d_by_dv_v5_v1_504 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 207);ahdlDoSetLineNum ((long) 207);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_20))), (_p_pcvd_64))));__tmpStkVar_1 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_64))));(_vsub_448) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 208);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pnwr1_88) - ((__FLOAT_DIV(((((_pnwr2_112) * ((((_vsub_448) - (_pnwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pnwr4_160)))) * ((((_vsub_448) - (_pnwr4_160))))))) + ((((_pnwr3_136) * (_pnwr3_136))))))))))))))));__tmpStkVar_2 = (((-(__FLOAT_DIV(((((((((((_pnwr2_112)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_448)) - ((_pnwr4_160)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))))))) * (((((_pnwr2_112)) * (((((_vsub_448)) - ((_pnwr4_160))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))), ((2.00000000000000000000e+00))))))))));(_p_ebodr_368) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 209);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_448) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pendr4_256)))) * ((((_vsub_448) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));__tmpStkVar_3 = (((-(__FLOAT_DIV(((((((((((_pendr2_208)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_448)) - ((_pendr4_256)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) * (((((_pendr2_208)) * (((((_vsub_448)) - ((_pendr4_256))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))), ((2.00000000000000000000e+00))))))))));(_p_eendr_408) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 210);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((((((2.00000000000000000000e+00)) * (((((((_p_ebodr_368) * (_prnw_280)))) + ((((_p_eendr_408) * (_pendr_304)))))))))), (_m_40))));__tmpStkVar_4 = ((__FLOAT_DIV((((((2.00000000000000000000e+00))) * ((((((((__tmpStkVar_2)) * ((_prnw_280))))) + (((((__tmpStkVar_3)) * ((_pendr_304)))))))))), (_m_40))));(_res_328) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 212);(_I_Static_v5_v1_512) += (__FLOAT_DIV(((getAcrossSolution2(_v5_12, _v1_20))), ((_res_328))));_Static_d_by_dv_v2_v1_488 += ((__FLOAT_DIV((((-(((__tmpStkVar_4)) * (((getAcrossSolution2(_v5_12, _v1_20)))))))), ((ahdlPow(((_res_328)), ((2.00000000000000000000e+00))))))));_Static_d_by_dv_v5_v1_504 += ((__FLOAT_DIV(((1.00000000000000000000e+00)), ((_res_328)))));}ahdlDoSetLineNum ((long) 214);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v5_12] -= _I_Static_v5_v1_512;
      ahdlStaticRHS[_v1_20] += _I_Static_v5_v1_512;
      ahdlStaticRHS_AbsSum[_v5_12] += ABS(_I_Static_v5_v1_512);
      ahdlStaticRHS_AbsSum[_v1_20] += ABS(_I_Static_v5_v1_512);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 480),_Static_d_by_dv_v2_v1_488);
      ahdlInterAddStaticQuartet(*(void**)(instData + 496),_Static_d_by_dv_v5_v1_504);
    return __msgSeverity__;
} /** end of dgncap_res1_DcFuncDerLoad **/

int dgncap_res1_DcFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v5_v1_512 = 0.0;
_Static_d_by_dv_v2_v1_488 = 0.0;
_Static_d_by_dv_v5_v1_504 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 207);ahdlDoSetLineNum ((long) 207);(_vsub_448) = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_20))), (_p_pcvd_64))));ahdlDoSetLineNum ((long) 208);(_p_ebodr_368) = ((((_pnwr1_88) - ((__FLOAT_DIV(((((_pnwr2_112) * ((((_vsub_448) - (_pnwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pnwr4_160)))) * ((((_vsub_448) - (_pnwr4_160))))))) + ((((_pnwr3_136) * (_pnwr3_136))))))))))))))));ahdlDoSetLineNum ((long) 209);(_p_eendr_408) = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_448) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pendr4_256)))) * ((((_vsub_448) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));ahdlDoSetLineNum ((long) 210);(_res_328) = ((__FLOAT_DIV((((((2.00000000000000000000e+00)) * (((((((_p_ebodr_368) * (_prnw_280)))) + ((((_p_eendr_408) * (_pendr_304)))))))))), (_m_40))));ahdlDoSetLineNum ((long) 212);(_I_Static_v5_v1_512) += (__FLOAT_DIV(((getAcrossSolution2(_v5_12, _v1_20))), ((_res_328))));}ahdlDoSetLineNum ((long) 214);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v5_12] -= _I_Static_v5_v1_512;
      ahdlStaticRHS[_v1_20] += _I_Static_v5_v1_512;
      ahdlStaticRHS_AbsSum[_v5_12] += ABS(_I_Static_v5_v1_512);
      ahdlStaticRHS_AbsSum[_v1_20] += ABS(_I_Static_v5_v1_512);
   }

    return __msgSeverity__;
} /** end of dgncap_res1_DcFuncLoad **/

int dgncap_res1_TranFuncDerLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v5_v1_512 = 0.0;
_Static_d_by_dv_v2_v1_488 = 0.0;
_Static_d_by_dv_v5_v1_504 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 207);ahdlDoSetLineNum ((long) 207);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_20))), (_p_pcvd_64))));__tmpStkVar_1 = ((__FLOAT_DIV(((1.00000000000000000000e+00)), (_p_pcvd_64))));(_vsub_448) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 208);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pnwr1_88) - ((__FLOAT_DIV(((((_pnwr2_112) * ((((_vsub_448) - (_pnwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pnwr4_160)))) * ((((_vsub_448) - (_pnwr4_160))))))) + ((((_pnwr3_136) * (_pnwr3_136))))))))))))))));__tmpStkVar_2 = (((-(__FLOAT_DIV(((((((((((_pnwr2_112)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_448)) - ((_pnwr4_160)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))))))) * (((((_pnwr2_112)) * (((((_vsub_448)) - ((_pnwr4_160))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_448)) - ((_pnwr4_160)))) * ((((_vsub_448)) - ((_pnwr4_160)))))))) + (((((_pnwr3_136)) * ((_pnwr3_136)))))))))), ((2.00000000000000000000e+00))))))))));(_p_ebodr_368) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 209);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_448) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pendr4_256)))) * ((((_vsub_448) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));__tmpStkVar_3 = (((-(__FLOAT_DIV(((((((((((_pendr2_208)) * ((__tmpStkVar_1))))) * (((ahdlSqrt(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) - (((((((((((((__INT_TO_DBL((2L))) * (((((_vsub_448)) - ((_pendr4_256)))))))) * ((__tmpStkVar_1))))) * (((ahdlSqrtDeriv(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))))))) * (((((_pendr2_208)) * (((((_vsub_448)) - ((_pendr4_256))))))))))))), ((ahdlPow(((ahdlSqrt(((((((((((_vsub_448)) - ((_pendr4_256)))) * ((((_vsub_448)) - ((_pendr4_256)))))))) + (((((_pendr3_232)) * ((_pendr3_232)))))))))), ((2.00000000000000000000e+00))))))))));(_p_eendr_408) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 210);{double __tempValueResultStatic;double __tempValueResultDynamic;
__tempValueResultStatic = ((__FLOAT_DIV((((((2.00000000000000000000e+00)) * (((((((_p_ebodr_368) * (_prnw_280)))) + ((((_p_eendr_408) * (_pendr_304)))))))))), (_m_40))));__tmpStkVar_4 = ((__FLOAT_DIV((((((2.00000000000000000000e+00))) * ((((((((__tmpStkVar_2)) * ((_prnw_280))))) + (((((__tmpStkVar_3)) * ((_pendr_304)))))))))), (_m_40))));(_res_328) = __tempValueResultStatic;}ahdlDoSetLineNum ((long) 212);(_I_Static_v5_v1_512) += (__FLOAT_DIV(((getAcrossSolution2(_v5_12, _v1_20))), ((_res_328))));_Static_d_by_dv_v2_v1_488 += ((__FLOAT_DIV((((-(((__tmpStkVar_4)) * (((getAcrossSolution2(_v5_12, _v1_20)))))))), ((ahdlPow(((_res_328)), ((2.00000000000000000000e+00))))))));_Static_d_by_dv_v5_v1_504 += ((__FLOAT_DIV(((1.00000000000000000000e+00)), ((_res_328)))));}ahdlDoSetLineNum ((long) 214);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v5_12] -= _I_Static_v5_v1_512;
      ahdlStaticRHS[_v1_20] += _I_Static_v5_v1_512;
      ahdlStaticRHS_AbsSum[_v5_12] += ABS(_I_Static_v5_v1_512);
      ahdlStaticRHS_AbsSum[_v1_20] += ABS(_I_Static_v5_v1_512);
   }

      ahdlInterAddStaticQuartet(*(void**)(instData + 480),_Static_d_by_dv_v2_v1_488);
      ahdlInterAddStaticQuartet(*(void**)(instData + 496),_Static_d_by_dv_v5_v1_504);
    return __msgSeverity__;
} /** end of dgncap_res1_TranFuncDerLoad **/

int dgncap_res1_TranFuncLoad(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


/*  Pre-Anal Load Code. */_I_Static_v5_v1_512 = 0.0;
_Static_d_by_dv_v2_v1_488 = 0.0;
_Static_d_by_dv_v5_v1_504 = 0.0;

/*  C Code Every Code. */{ahdlDoSetLineNum ((long) 207);ahdlDoSetLineNum ((long) 207);(_vsub_448) = ((__FLOAT_DIV(((getAcrossSolution2(_v2_28, _v1_20))), (_p_pcvd_64))));ahdlDoSetLineNum ((long) 208);(_p_ebodr_368) = ((((_pnwr1_88) - ((__FLOAT_DIV(((((_pnwr2_112) * ((((_vsub_448) - (_pnwr4_160))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pnwr4_160)))) * ((((_vsub_448) - (_pnwr4_160))))))) + ((((_pnwr3_136) * (_pnwr3_136))))))))))))))));ahdlDoSetLineNum ((long) 209);(_p_eendr_408) = ((((_pendr1_184) - ((__FLOAT_DIV(((((_pendr2_208) * ((((_vsub_448) - (_pendr4_256))))))), ((ahdlSqrt(((((((((((_vsub_448) - (_pendr4_256)))) * ((((_vsub_448) - (_pendr4_256))))))) + ((((_pendr3_232) * (_pendr3_232))))))))))))))));ahdlDoSetLineNum ((long) 210);(_res_328) = ((__FLOAT_DIV((((((2.00000000000000000000e+00)) * (((((((_p_ebodr_368) * (_prnw_280)))) + ((((_p_eendr_408) * (_pendr_304)))))))))), (_m_40))));ahdlDoSetLineNum ((long) 212);(_I_Static_v5_v1_512) += (__FLOAT_DIV(((getAcrossSolution2(_v5_12, _v1_20))), ((_res_328))));}ahdlDoSetLineNum ((long) 214);   if (ahdlWhatsNeeded IS devStaticFuncNeeded) {
      ahdlStaticRHS[_v5_12] -= _I_Static_v5_v1_512;
      ahdlStaticRHS[_v1_20] += _I_Static_v5_v1_512;
      ahdlStaticRHS_AbsSum[_v5_12] += ABS(_I_Static_v5_v1_512);
      ahdlStaticRHS_AbsSum[_v1_20] += ABS(_I_Static_v5_v1_512);
   }

    return __msgSeverity__;
} /** end of dgncap_res1_TranFuncLoad **/

int dgncap_res1_NoiseLoadBiasDep(int anal_mode, char* instData, char* modelData, char** stringList) {

int __msgSeverity__ = 0;
double	__tmpStkVar_4 = 0.0;
double	__tmpStkVar_3 = 0.0;
double	__tmpStkVar_2 = 0.0;
double	__tmpStkVar_1 = 0.0;


    return __msgSeverity__;
} /** end of dgncap_res1_NoiseLoadBiasDep **/

