/** 3893859583 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DGNCAP_CAP_INST_STATIC_H
#define DGNCAP_CAP_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_vp_vn_1144	(*((double *) &instData [1144]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_vp_vn_1136	(*((double *) &instData [1136]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Dynamic_d_by_dv_vp_vn_1128	(*((double *) &instData [1128]))	/* Branch Load Group : Size = 8 bytes. */
#define _testvolt_1088	(*((double *) &instData [1088]))	/* VT_REAL : Size = 8 bytes. */
#define _v1_1048	(*((double *) &instData [1048]))	/* VT_REAL : Size = 8 bytes. */
#define _qmaxfrl_1008	(*((double *) &instData [1008]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalfrl_968	(*((double *) &instData [968]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrgl2_928	(*((double *) &instData [928]))	/* VT_REAL : Size = 8 bytes. */
#define _qfrgl1_888	(*((double *) &instData [888]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalcg_848	(*((double *) &instData [848]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc5_808	(*((double *) &instData [808]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc4_768	(*((double *) &instData [768]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc3_728	(*((double *) &instData [728]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc2_688	(*((double *) &instData [688]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc1_648	(*((double *) &instData [648]))	/* VT_REAL : Size = 8 bytes. */
#define _qcalc_608	(*((double *) &instData [608]))	/* VT_REAL : Size = 8 bytes. */
#define _pcofl_584	(*((double *) &instData [584]))	/* VT_REAL : Size = 8 bytes. */
#define _deltemp_560	(*((double *) &instData [560]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4tc_536	(*((double *) &instData [536]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3tc_512	(*((double *) &instData [512]))	/* VT_REAL : Size = 8 bytes. */
#define _pc0tc_488	(*((double *) &instData [488]))	/* VT_REAL : Size = 8 bytes. */
#define _pcof_464	(*((double *) &instData [464]))	/* VT_REAL : Size = 8 bytes. */
#define _pfrac_c_440	(*((double *) &instData [440]))	/* VT_REAL : Size = 8 bytes. */
#define _pcg_416	(*((double *) &instData [416]))	/* VT_REAL : Size = 8 bytes. */
#define _pcfl4_392	(*((double *) &instData [392]))	/* VT_REAL : Size = 8 bytes. */
#define _pcfl3_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _pcfl2_344	(*((double *) &instData [344]))	/* VT_REAL : Size = 8 bytes. */
#define _pcfl1_320	(*((double *) &instData [320]))	/* VT_REAL : Size = 8 bytes. */
#define _pc10_296	(*((double *) &instData [296]))	/* VT_REAL : Size = 8 bytes. */
#define _pc9_272	(*((double *) &instData [272]))	/* VT_REAL : Size = 8 bytes. */
#define _pc8_248	(*((double *) &instData [248]))	/* VT_REAL : Size = 8 bytes. */
#define _pc7_224	(*((double *) &instData [224]))	/* VT_REAL : Size = 8 bytes. */
#define _pc6_200	(*((double *) &instData [200]))	/* VT_REAL : Size = 8 bytes. */
#define _pc5_176	(*((double *) &instData [176]))	/* VT_REAL : Size = 8 bytes. */
#define _pc4_152	(*((double *) &instData [152]))	/* VT_REAL : Size = 8 bytes. */
#define _pc3_128	(*((double *) &instData [128]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_104	(*((double *) &instData [104]))	/* VT_REAL : Size = 8 bytes. */
#define _pc2_80	(*((double *) &instData [80]))	/* VT_REAL : Size = 8 bytes. */
#define _pc1_56	(*((double *) &instData [56]))	/* VT_REAL : Size = 8 bytes. */
#define _m_32	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [32]))	/* VT_REAL : Size = 8 bytes. */
#define _vn_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _vp_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DGNCAP_CAP_INST_STATIC_H */
