/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#include "ahdlcmi.h"

int ahdlBsourceInterfaceVersion() {
   return 1; /* Only used when version >= spectre's BsourceInterfaceVersion */
}

extern int dgncap_cap_DcFuncDerLoad(int, char*, char*, char**);
extern int dgncap_cap_DcFuncLoad(int, char*, char*, char**);
extern int dgncap_cap_TranFuncDerLoad(int, char*, char*, char**);
extern int dgncap_cap_TranFuncLoad(int, char*, char*, char**);
extern int dgncap_cap_NoiseLoadBiasDep(int, char*, char*, char**);

int dgncap_cap_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        dgncap_cap_DcFuncDerLoad,  
                        dgncap_cap_DcFuncLoad,     
                        dgncap_cap_TranFuncDerLoad,
                        dgncap_cap_TranFuncLoad,   
                        dgncap_cap_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
extern int dgncap_cur_DcFuncDerLoad(int, char*, char*, char**);
extern int dgncap_cur_DcFuncLoad(int, char*, char*, char**);
extern int dgncap_cur_TranFuncDerLoad(int, char*, char*, char**);
extern int dgncap_cur_TranFuncLoad(int, char*, char*, char**);
extern int dgncap_cur_NoiseLoadBiasDep(int, char*, char*, char**);

int dgncap_cur_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        dgncap_cur_DcFuncDerLoad,  
                        dgncap_cur_DcFuncLoad,     
                        dgncap_cur_TranFuncDerLoad,
                        dgncap_cur_TranFuncLoad,   
                        dgncap_cur_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
extern int dgncap_frcap_DcFuncDerLoad(int, char*, char*, char**);
extern int dgncap_frcap_DcFuncLoad(int, char*, char*, char**);
extern int dgncap_frcap_TranFuncDerLoad(int, char*, char*, char**);
extern int dgncap_frcap_TranFuncLoad(int, char*, char*, char**);
extern int dgncap_frcap_NoiseLoadBiasDep(int, char*, char*, char**);

int dgncap_frcap_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        dgncap_frcap_DcFuncDerLoad,  
                        dgncap_frcap_DcFuncLoad,     
                        dgncap_frcap_TranFuncDerLoad,
                        dgncap_frcap_TranFuncLoad,   
                        dgncap_frcap_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
extern int dgncap_res1_DcFuncDerLoad(int, char*, char*, char**);
extern int dgncap_res1_DcFuncLoad(int, char*, char*, char**);
extern int dgncap_res1_TranFuncDerLoad(int, char*, char*, char**);
extern int dgncap_res1_TranFuncLoad(int, char*, char*, char**);
extern int dgncap_res1_NoiseLoadBiasDep(int, char*, char*, char**);

int dgncap_res1_InstallDeviceBindings(struct ahdlDevDescData *desc) {

   ahdlBindDevDescFuncs(desc,
                        dgncap_res1_DcFuncDerLoad,  
                        dgncap_res1_DcFuncLoad,     
                        dgncap_res1_TranFuncDerLoad,
                        dgncap_res1_TranFuncLoad,   
                        dgncap_res1_NoiseLoadBiasDep
                       );
   return 1; /** success **/
}
