/** 2808457389 **/
/***********************************************************************************
 ** Copyright (c) 2003 Cadence Design Systems, Inc. All rights reserved.          **
 **                                                                               **
 ** This work may not be copied, modified, re-published, uploaded, executed, or   **
 ** distributed in any way, in any medium, whether in whole or in part, without   **
 ** prior written permission from Cadence Design Systems, Inc.                    **
 **                                                                               **
 ** This file is automatically generated and will be overwritten. The interfaces  **
 ** used within this generated code are subject to change without notice.         **
 ***********************************************************************************/
#ifndef DGNCAP_RES1_INST_STATIC_H
#define DGNCAP_RES1_INST_STATIC_H

#include <math.h>
#include <stdlib.h>

#include "ahdlcmi.h"


#define _I_Dynamic_v5_v1_520	(*((double *) &instData [520]))	/* VT_BRANCH : Size = 8 bytes. */
#define _I_Static_v5_v1_512	(*((double *) &instData [512]))	/* VT_BRANCH : Size = 8 bytes. */
#define _Static_d_by_dv_v5_v1_504	(*((double *) &instData [504]))	/* Branch Load Group : Size = 8 bytes. */
#define _Static_d_by_dv_v2_v1_488	(*((double *) &instData [488]))	/* Branch Load Group : Size = 8 bytes. */
#define _vsub_448	(*((double *) &instData [448]))	/* VT_REAL : Size = 8 bytes. */
#define _p_eendr_408	(*((double *) &instData [408]))	/* VT_REAL : Size = 8 bytes. */
#define _p_ebodr_368	(*((double *) &instData [368]))	/* VT_REAL : Size = 8 bytes. */
#define _res_328	(*((double *) &instData [328]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr_304	(*((double *) &instData [304]))	/* VT_REAL : Size = 8 bytes. */
#define _prnw_280	(*((double *) &instData [280]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr4_256	(*((double *) &instData [256]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr3_232	(*((double *) &instData [232]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr2_208	(*((double *) &instData [208]))	/* VT_REAL : Size = 8 bytes. */
#define _pendr1_184	(*((double *) &instData [184]))	/* VT_REAL : Size = 8 bytes. */
#define _pnwr4_160	(*((double *) &instData [160]))	/* VT_REAL : Size = 8 bytes. */
#define _pnwr3_136	(*((double *) &instData [136]))	/* VT_REAL : Size = 8 bytes. */
#define _pnwr2_112	(*((double *) &instData [112]))	/* VT_REAL : Size = 8 bytes. */
#define _pnwr1_88	(*((double *) &instData [88]))	/* VT_REAL : Size = 8 bytes. */
#define _p_pcvd_64	(*((double *) &instData [64]))	/* VT_REAL : Size = 8 bytes. */
#define _m_40	(*((double *) &instData [40]))	/* VT_REAL : Size = 8 bytes. */
#define m	(*((double *) &instData [40]))	/* VT_REAL : Size = 8 bytes. */
#define _v2_28	(*((long *) &instData [28]))	/* VT_NODE : Size = 4 bytes. */
#define _v1_20	(*((long *) &instData [20]))	/* VT_NODE : Size = 4 bytes. */
#define _v5_12	(*((long *) &instData [12]))	/* VT_NODE : Size = 4 bytes. */


#endif /* DGNCAP_RES1_INST_STATIC_H */
